# this file is managed by dry-rb/devtools project

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - spec/support/coverage.rb
    - spec/support/warnings.rb
    - Gemfile.devtools
    - "*.gemspec"

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Lint/HandleExceptions:
  Exclude:
    - "spec/spec_helper.rb"

Lint/BooleanSymbol:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/dry-*.rb"

Naming/MethodName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 12

Style/AccessModifierDeclarations:
  Enabled: false

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - "spec/**/*_spec.rb"

Style/ConditionalAssignment:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/SymbolArray:
  Exclude:
    - "spec/**/*_spec.rb"

Style/TrailingUnderscoreVariable:
  Enabled: false
